name: AntiAdminAbuse
version: 1.0.0
main: com.antiabuse.AntiAdminAbusePlugin
api-version: "1.21"
author: Stxrlight (@Stan.GB)
description: Anti-admin abuse plugin that logs commands and obfuscates coordinates

dependencies:
  server:
    - name: paper
      load: BEFORE
      required: true

permissions:
  antiabuse.view:
    description: Allows viewing command history, operator list, and using spy features
    default: true
  antiabuse.admin:
    description: Allows clearing all records and reloading the plugin
    default: op
  antiabuse.exempt:
    description: Exempts player from command logging
    default: false 